# Generated by Django 5.1 on 2024-09-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("sl_no", models.IntegerField(primary_key=True, serialize=False)),
                ("gender", models.CharField(max_length=100)),
                ("ssc_p", models.FloatField()),
                ("ssc_b", models.CharField(max_length=100)),
                ("hsc_p", models.FloatField()),
                ("hsc_b", models.CharField(max_length=100)),
                ("degree_p", models.FloatField()),
                ("degree_t", models.CharField(max_length=100)),
                ("workex", models.CharField(max_length=100, null=True)),
                ("etest_p", models.FloatField(null=True)),
                ("specialisation", models.CharField(max_length=100)),
                ("mba_p", models.FloatField(null=True)),
                ("status", models.CharField(max_length=100)),
                ("salary", models.IntegerField()),
                ("Name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("mobile", models.IntegerField()),
                ("DOB", models.DateTimeField()),
                ("school_10", models.CharField(max_length=200)),
                ("ssc_y", models.IntegerField()),
                ("degree", models.CharField(max_length=200)),
                ("university", models.CharField(max_length=200)),
                ("Stream", models.CharField(max_length=200)),
                ("degree_passoutYear", models.CharField(max_length=200)),
                ("workex_company", models.CharField(max_length=200)),
                ("skills", models.CharField(max_length=500)),
                ("certificates", models.CharField(max_length=500)),
                ("resume", models.FileField(null=True, upload_to="")),
            ],
        ),
    ]
