# Generated by Django 5.1 on 2024-09-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predict_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="school_10",
        ),
        migrations.AddField(
            model_name="users",
            name="hsc_y",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
