# Generated by Django 5.1 on 2024-09-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predict_app", "0002_remove_users_school_10_users_hsc_y"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="resume",
            field=models.FileField(blank=True, default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
