# Generated by Django 5.1 on 2024-09-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predict_app", "0003_alter_users_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="DOB",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="users",
            name="etest_p",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="users",
            name="mba_p",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="users",
            name="workex",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
